config:
  SERVER_PORT: "8080"
  ZIPKIN_URL: "http://tempo-grafana-tempo-distributor.tempo.svc.cluster.local:9411"
  LOKI_DISTRIBUTOR_URL: "http://loki-grafana-loki-distributor.loki.svc.cluster.local:3100/loki/api/v1/push"

replicaCount: 1

image:
  name: service-template
  pullPolicy: Always

service:
  type: ClusterIP
  targetPort: 8081
